### ISSUE TITLE
Add Automatic Swagger yaml generation

### ISSUE THREAD

**Issue by tsukhu** [ERS-HCL/nxplorerjs-microservice-starter#20]
Use swagger-jsdoc to auto generate swagger documentation

**Comment by tsukhu** [comment]
While this feature is nice .. It will cause the swagger spec to be distributed across each controller file and difficult to edit in one place using the swagger editor .. so will decide after experimenting with this if it is really required or not

**Comment by agalazis** [comment]
Another way is tsoa it seems overly complicated to me

**Comment by tsukhu** [comment]
@agalazis thank you for the valuable suggestion. tsoa is a nice option. However it will need to see if it will work alongside the inversify annotations being used currently. As you said the current yaml file is the simpler way. The plan is to create a feature branch and then try this out with tsoa and see how it works

**Comment by tsukhu** [comment]
Looking at the compatibility and the inversify ecosystem , planning to try out https://github.com/olivierlsc/swagger-express-ts

**Comment by tsukhu** [comment]
The implementation will be left as API first mode. i.e. define API definition first , use mocks till implementation
