### ISSUE TITLE
Swagger validation not working

### ISSUE THREAD

**Issue by kovaz01** [ERS-HCL/nxplorerjs-microservice-starter#235]
* **I'm submitting a ...**
[* ] bug report

* **Do you want to request a *feature* or report a *bug*?**
want to report a bug

* **What is the current behavior?**
when I want to validate a request, for example by max size. I added the condition to Yaml file and invalid request still working 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- nxplorer version: 1.5.6
- other environment details

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. npm , github, stackoverflow etc)

**Comment by tsukhu** [comment]
PR #236 fixes this.
